# This is a configuration file for Wrangler, the command-line interface for Cloudflare Workers.
# The presence of this file tells Cloudflare Pages that this is an advanced project
# with a backend Worker function.

name = "vedictherapist"
main = "functions/index.js" # **THE FIX: Point to the new standard directory**
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
